### ISSUE TITLE
Update from 1.0.4 to 1.0.7: undefined method StandaloneView::setRequest

### ISSUE THREAD

**Issue by linawolf** [b13/twoclickmedia#14]
I just updated twoclickmedia from 1.0.4 to 1.0.7. In TYPO3 v11 with PHP 8.0

I now get the error 

```
Call to undefined method TYPO3\CMS\Fluid\View\StandaloneView::setRequest()
in /var/www/html/public/typo3conf/ext/twoclickmedia/Classes/Resource/Rendering/YouTubeRenderer.php line 90
```

After Downgrading back to 1.0.4 it works again

I think it might be related to https://github.com/b13/twoclickmedia/pull/13

**Comment by bmack** [comment]
I guess we need a check for setRequest for v10 compatibility.

```if (method_exists()```

**Comment by achimfritz** [comment]
fixed with https://github.com/b13/twoclickmedia/commit/1f726f63da498bfeeaacb0542a4ac2027ebe96ee
