### ISSUE TITLE
Cannot handle sys_file_reference

### ISSUE THREAD

**Issue by jschlier** [b13/twoclickmedia#5]
The patch #2  introduced for #1 added logic to differentiate between files and file references.
The result of this logic is not passed to the rendered iframe, resulting in a "hardcoded" expectation of a File object.

Passing in a FileReference uid results in either the wrong image being displayed (if an image with the same UID exists), or an exception that the file could not be found.

**Comment by achimfritz** [comment]
fixed with https://github.com/b13/twoclickmedia/pull/6/commits/a0549151d6950688406fdc702904ea37a35286a1
